id: PA061E4FE
initial_creation_type: input
source_metadata:
  title: Namkha Drimed Rinpoche Series
  language: bo
  description: 'Texts by and about Namkha Drimed Rabjam Rinpoche (nam mkha'' dri med
    rab ''byams rin po che, b. 1938), the modern tertön renowned for his connection
    with King Gesar:'
  volume:
    d28bceb31c1c4e61b3624b4ee393d41f:
      title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T00:58:29.392636'
last_modified_at: '2022-03-01T00:58:29.392639'
statistics:
  total_words: 221
  total_non_words: 17
quality:
  non_words_ratio: 0.08
